# Generated by Django 3.0.8 on 2021-05-03 06:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210428_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
