# Generated by Django 3.0.8 on 2021-05-09 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_myblog_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
