# Generated by Django 3.0.8 on 2021-05-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210509_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
