# Generated by Django 3.0.8 on 2021-05-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210509_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
