# Generated by Django 3.0.8 on 2021-05-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_myblog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='category',
            field=models.CharField(choices=[('politics', 'politics'), ('Sports', 'Sports'), ('Busines', 'Busines'), ('Education', 'Education'), ('Other', 'Other'), ('Entertainment', 'Entertainment')], default='Other', max_length=15),
        ),
    ]
