# Generated by Django 3.0.2 on 2021-06-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210531_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
