# Generated by Django 3.0.2 on 2021-06-16 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0023_auto_20210614_0026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='MyBlog',
        ),
    ]
